[control]
10.0.0.10 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=~/.ssh/google_compute_engine

[compute]
10.0.0.20 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=~/.ssh/google_compute_engine

[network]
10.0.0.30 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=~/.ssh/google_compute_engine

[storage]
10.0.0.40 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=~/.ssh/google_compute_engine

[loadbalancer]
10.0.0.10 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=~/.ssh/google_compute_engine

[baremetal]

[nova-novncproxy]
[nova-spicehtml5proxy]
[nova-serialproxy]
[nova-conductor]
[nova-compute-ironic]
[nova-super-conductor]

[neutron-server]
[neutron-dhcp-agent]
[neutron-l3-agent]
[neutron-metadata-agent]
[neutron-openvswitch-agent]
[neutron-ovn-metadata-agent]
[neutron-bgp-dragent]
[neutron-infoblox-ipam-agent]
[neutron-metering-agent]
[ironic-neutron-agent]

[glance-api]
10.0.0.10

[heat-api]
10.0.0.10

[heat-api-cfn]
10.0.0.10

[heat-engine]
10.0.0.10

[horizon]
10.0.0.10

[keystone]
10.0.0.10

[mariadb]
10.0.0.10

[placement-api]
10.0.0.10

[nova-api]
10.0.0.10

[nova-scheduler]
10.0.0.10

[rabbitmq]
10.0.0.10

[memcached]
10.0.0.10

[redis]
10.0.0.10
